apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: guestbook
spec:
  clusterSelector:
    matchLabels:
      env: fv
  policyRefs:
  - kind: ConfigMap
    name: database
    namespace: default
  - kind: ConfigMap
    name: frontend
    namespace: default