apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-manager
  namespace: projectsveltos
spec:
  template:
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --report-mode=0
        - --agent-in-mgmt-cluster
        - --shard-key=
        - --v=5
        - --version=dev
        name: manager