apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-manager
  namespace: projectsveltos
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --diagnostics-address=:8443
            - --shard-key=
            - --capi-onboard-annotation=
            - --v=5
            - --version=main
            - --agent-in-mgmt-cluster=true
