apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-controller
  namespace: projectsveltos
spec:
  template:
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --v=5
        - --report-mode=0
        - --agent-in-mgmt-cluster
        name: manager