# Those YAML are all needed when sveltos-agent is started in the management cluster. 
# Those are not installed by classifier when deploying sveltos-agent in the management
# cluster to avoid granting classifier extra permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sveltos-agent-manager
  namespace: projectsveltos
---
# When running in the management cluster, sveltos-agent needs to access Secret containing
# Kubeconfig for managed cluster (and consequently access Cluster/SveltosCluster to verify existance)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sveltos-agent-manager-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - debuggingconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - sveltosclusters
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sveltos-agent-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sveltos-agent-manager-role
subjects:
- kind: ServiceAccount
  name: sveltos-agent-manager
  namespace: projectsveltos
