---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-cnpg
spec:
  clusterSelector:
    matchLabels:
      type: services
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    https://cloudnative-pg.github.io/charts
    repositoryName:   cloudnative-pg 
    chartName:        cloudnative-pg/cloudnative-pg
    chartVersion:     0.22.1 
    releaseName:      cnpg
    releaseNamespace: cnpg-system
    helmChartAction:  Install
