---
# This default Classifier is needed so any cluster
# where sveltos-agent is installed is labeled
apiVersion: lib.projectsveltos.io/v1beta1
kind: Classifier
metadata:
  name: default-classifier
spec:
  classifierLabels:
   - key: sveltos-agent
     value: present