{
 "title": "Sveltos Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Connectivity Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "projectsveltos_cluster_connectivity_status",
     "legendFormat": "{{cluster_namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Kubernetes Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "projectsveltos_kubernetes_version_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Helm Charts Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "projectsveltos_program_charts_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Resources Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "projectsveltos_program_resources_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Deploy Helm Charts in a Profile ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(projectsveltos_program_charts_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(projectsveltos_program_charts_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Time to Deploy Resources in a Profile ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(projectsveltos_program_resources_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(projectsveltos_program_resources_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Time to Deploy Helm Charts in a Profile - Histogram",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "projectsveltos_program_charts_time_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to Deploy Resources in a Profile - Histogram",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "projectsveltos_program_resources_time_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Deploy Helm Charts in a Profile- Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(projectsveltos_program_charts_time_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deploy Resources in a Profile - Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(projectsveltos_program_resources_time_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "projectsveltos_reconcile_operations_total",
     "legendFormat": "{{cluster_type}}/{{cluster_namespace}}/{{cluster_name}} - {{feature}}"
    }
   ]
  },
  {
   "title": "Drifts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "projectsveltos_total_drifts",
     "legendFormat": "{{cluster_type}}/{{cluster_namespace}}/{{cluster_name}} - {{feature}}"
    }
   ]
  }
 ]
}