apiVersion: v1
kind: ServiceAccount
metadata:
    name: addon-controller
    namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: addon-controller-role-extra
    namespace: projectsveltos
rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - list
        - create
        - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterconfiguration-editor-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterconfiguration-viewer-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterprofile-editor-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterprofile-viewer-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterreport-editor-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterreports
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterreports/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clusterreport-viewer-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterreports
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterreports/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clustersummary-editor-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clustersummaries
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clustersummaries/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-clustersummary-viewer-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clustersummaries
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clustersummaries/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-controller-role
rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
        - update
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - get
        - impersonate
        - list
        - watch
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
    - apiGroups:
        - cluster.x-k8s.io
      resources:
        - clusters
        - clusters/status
        - machines
        - machines/status
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations
        - clusterreports
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterconfigurations/status
        - clusterreports/status
      verbs:
        - get
        - list
        - update
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles
        - clusterpromotions
        - clustersummaries
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles/finalizers
        - clustersummaries/finalizers
        - profiles/finalizers
      verbs:
        - patch
        - update
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterprofiles/status
        - clusterpromotions/status
        - clustersummaries/status
        - profiles/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - clusterpromotions/finalizers
      verbs:
        - update
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - profiles
      verbs:
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - controlplane.cluster.x-k8s.io
      resources:
        - kubeadmcontrolplanes
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extension.projectsveltos.io
      resources:
        - jsonnetsources
        - yttsources
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - infrastructure.cluster.x-k8s.io
      resources:
        - '*'
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - clusterhealthchecks
        - configurationgroups/status
        - debuggingconfigurations
        - eventtriggers
        - sveltosclusters
        - sveltosclusters/status
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - clustersets
        - configurationbundles
        - configurationgroups
        - reloaders
        - resourcesummaries
        - sets
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - clustersets/finalizers
        - sets/finalizers
      verbs:
        - update
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - clustersets/status
        - sets/status
      verbs:
        - get
        - patch
        - update
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - configurationbundles/status
      verbs:
        - get
        - list
        - update
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - resourcesummaries/status
      verbs:
        - get
        - list
        - update
    - apiGroups:
        - source.toolkit.fluxcd.io
      resources:
        - buckets
        - buckets/status
        - gitrepositories
        - gitrepositories/status
        - ocirepositories
        - ocirepositories/status
      verbs:
        - get
        - list
        - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: addon-controller-role-extra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: addon-controller
        app.kubernetes.io/instance: profile-editor-role
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: clusterrole
        app.kubernetes.io/part-of: addon-controller
    name: addon-profile-editor-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - profiles
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - profiles/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: addon-controller
        app.kubernetes.io/instance: profile-viewer-role
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: clusterrole
        app.kubernetes.io/part-of: addon-controller
    name: addon-profile-viewer-role
rules:
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - profiles
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - config.projectsveltos.io
      resources:
        - profiles/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: addon-controller-rolebinding-extra
    namespace: projectsveltos
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: addon-controller-role-extra
subjects:
    - kind: ServiceAccount
      name: addon-controller
      namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: addon-controller-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: addon-controller-role
subjects:
    - kind: ServiceAccount
      name: addon-controller
      namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: addon-controller-rolebinding-extra
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: addon-controller-role-extra
subjects:
    - kind: ServiceAccount
      name: addon-controller
      namespace: projectsveltos
---
apiVersion: v1
kind: Service
metadata:
    labels:
        control-plane: addon-controller
    name: addon-controller
    namespace: projectsveltos
spec:
    ports:
        - name: metrics
          port: 80
          protocol: TCP
          targetPort: 8443
    selector:
        control-plane: addon-controller
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        control-plane: addon-controller
    name: addon-controller
    namespace: projectsveltos
spec:
    replicas: 1
    selector:
        matchLabels:
            control-plane: addon-controller
    template:
        metadata:
            annotations:
                kubectl.kubernetes.io/default-container: controller
            labels:
                control-plane: addon-controller
        spec:
            containers:
                - args:
                    - --diagnostics-address=:8443
                    - --report-mode=0
                    - --shard-key=
                    - --capi-onboard-annotation=
                    - --v=5
                    - --version=v1.3.1
                    - --agent-in-mgmt-cluster=false
                  command:
                    - /manager
                  env:
                    - name: GOMEMLIMIT
                      valueFrom:
                        resourceFieldRef:
                            resource: limits.memory
                    - name: GOMAXPROCS
                      valueFrom:
                        resourceFieldRef:
                            resource: limits.cpu
                  image: docker.io/projectsveltos/addon-controller:v1.3.1
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /healthz
                        port: healthz
                        scheme: HTTP
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: controller
                  ports:
                    - containerPort: 8443
                      name: metrics
                      protocol: TCP
                    - containerPort: 9440
                      name: healthz
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /readyz
                        port: healthz
                        scheme: HTTP
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  resources:
                    requests:
                        memory: 256Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    seccompProfile:
                        type: RuntimeDefault
                  volumeMounts:
                    - mountPath: /tmp
                      name: tmp
            securityContext:
                runAsNonRoot: true
            serviceAccountName: addon-controller
            terminationGracePeriodSeconds: 10
            volumes:
                - emptyDir: {}
                  name: tmp
---
