apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: shard-controller
        app.kubernetes.io/instance: controller-manager-sa
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: serviceaccount
        app.kubernetes.io/part-of: shard-controller
    name: shard-controller
    namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: shard-controller-role-extra
    namespace: projectsveltos
rules:
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: shard-manager-role
rules:
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
    - apiGroups:
        - cluster.x-k8s.io
      resources:
        - clusters
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - cluster.x-k8s.io
      resources:
        - clusters/status
      verbs:
        - get
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - debuggingconfigurations
        - sveltosclusters
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - sveltosclusters/status
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: shard-controller-rolebinding-extra
    namespace: projectsveltos
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: shard-controller-role-extra
subjects:
    - kind: ServiceAccount
      name: shard-controller
      namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: shard-controller
        app.kubernetes.io/instance: manager-rolebinding
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: clusterrolebinding
        app.kubernetes.io/part-of: shard-controller
    name: shard-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: shard-manager-role
subjects:
    - kind: ServiceAccount
      name: shard-controller
      namespace: projectsveltos
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        control-plane: shard-controller
    name: shard-controller
    namespace: projectsveltos
spec:
    replicas: 1
    selector:
        matchLabels:
            control-plane: shard-controller
    template:
        metadata:
            annotations:
                kubectl.kubernetes.io/default-container: manager
            labels:
                control-plane: shard-controller
        spec:
            containers:
                - args:
                    - --diagnostics-address=:8443
                    - --v=5
                    - --report-mode=0
                  command:
                    - /manager
                  image: docker.io/projectsveltos/shard-controller:v0.43.0
                  livenessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /healthz
                        port: healthz
                        scheme: HTTP
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: manager
                  ports:
                    - containerPort: 8443
                      name: metrics
                      protocol: TCP
                    - containerPort: 9440
                      name: healthz
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    httpGet:
                        path: /readyz
                        port: healthz
                        scheme: HTTP
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  resources:
                    limits:
                        cpu: 500m
                        memory: 256Mi
                    requests:
                        cpu: 10m
                        memory: 128Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
            securityContext:
                runAsNonRoot: true
            serviceAccountName: shard-controller
            terminationGracePeriodSeconds: 10
---
