apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        control-plane: techsupport
    name: techsupport-controller
    namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: techsupport-role
rules:
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - debuggingconfigurations
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - techsupports
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - techsupports/finalizers
      verbs:
        - update
    - apiGroups:
        - lib.projectsveltos.io
      resources:
        - techsupports/status
      verbs:
        - get
        - patch
        - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: techsupport-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: techsupport-role
subjects:
    - kind: ServiceAccount
      name: techsupport-controller
      namespace: projectsveltos
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        control-plane: techsupport
    name: techsupport-controller
    namespace: projectsveltos
spec:
    replicas: 1
    selector:
        matchLabels:
            control-plane: techsupport
    template:
        metadata:
            annotations:
                kubectl.kubernetes.io/default-container: controller
            labels:
                control-plane: techsupport
        spec:
            containers:
                - args:
                    - --v=5
                  command:
                    - /manager
                  image: docker.io/projectsveltos/techsupport:v0.52.3
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8081
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: controller
                  readinessProbe:
                    httpGet:
                        path: /readyz
                        port: 8081
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
            securityContext:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            serviceAccountName: techsupport-controller
            terminationGracePeriodSeconds: 10
---
