name: CI build main documentation
on:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install Dependencies
      run: |
        pip install zensical==0.0.32
        pip install git+https://github.com/squidfunk/mike.git
    - name: Setup Docs Deploy
      run: |
        git config --global user.name "Sveltos Docu Deploy"
        git config --global user.email "docu@projectsveltos.io"
    - name: Build Docs Website
      run: |
        mike deploy --push main --update-aliases
        mike set-default main --push
